/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.Ingredient;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-11T13:23:56.479615-07:00[America/Los_Angeles]")
@Api(value = "ingredients", description = "the ingredients API")
public interface IngredientsApi {

    @ApiOperation(value = "removes an ingredient from the database", nickname = "deleteIngredientById", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Item successfully deleted"),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/ingredients/{ingredientId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteIngredientById(@Min(0)@ApiParam(value = "an ingredient's unique ID",required=true, allowableValues="") @PathVariable("ingredientId") Integer ingredientId);


    @ApiOperation(value = "returns a specific pizza ingredient", nickname = "getIngredientById", notes = "", response = Ingredient.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "ingredient found", response = Ingredient.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/ingredients/{ingredientId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Ingredient> getIngredientById(@Min(0)@ApiParam(value = "an ingredient's unique ID",required=true, allowableValues="") @PathVariable("ingredientId") Integer ingredientId);


    @ApiOperation(value = "creates a new ingredient", nickname = "newIngredient", notes = "", response = Ingredient.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "ingredient created", response = Ingredient.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class) })
    @RequestMapping(value = "/ingredients",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ingredient> newIngredient(@ApiParam(value = "A JSON encoded ingredient object" ,required=true )  @Valid @RequestBody Ingredient body);


    @ApiOperation(value = "updates a specific pizza ingredient", nickname = "updateIngredientById", notes = "", response = Ingredient.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "ingredient updated", response = Ingredient.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/ingredients/{ingredientId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Ingredient> updateIngredientById(@ApiParam(value = "A JSON encoded ingredient object" ,required=true )  @Valid @RequestBody Ingredient body,@Min(0)@ApiParam(value = "an ingredient's unique ID",required=true, allowableValues="") @PathVariable("ingredientId") Integer ingredientId);

}
