/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.Order;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-11T13:23:56.479615-07:00[America/Los_Angeles]")
@Api(value = "orders", description = "the orders API")
public interface OrdersApi {

    @ApiOperation(value = "adds a new order to the database", nickname = "addOrder", notes = "This operation adds an order to the database when a customer makes an order.", response = Order.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "item created", response = Order.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class) })
    @RequestMapping(value = "/orders",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Order> addOrder(@ApiParam(value = "An order to add" ,required=true )  @Valid @RequestBody Order body);


    @ApiOperation(value = "retrieves an order", nickname = "getOrderById", notes = "By passing in a valid ID, you can find an order in the database.", response = Order.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "order found", response = Order.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/orders/{orderId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Order> getOrderById(@Min(0)@ApiParam(value = "an order's unique ID",required=true, allowableValues="") @PathVariable("orderId") Integer orderId);


    @ApiOperation(value = "updates an order", nickname = "updateOrderById", notes = "", response = Order.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "order updated", response = Order.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/orders/{orderId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Order> updateOrderById(@ApiParam(value = "A JSON encoded Order object" ,required=true )  @Valid @RequestBody Order body,@Min(0)@ApiParam(value = "an order's unique ID",required=true, allowableValues="") @PathVariable("orderId") Integer orderId);

}
