/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.Pizza;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-11T13:23:56.479615-07:00[America/Los_Angeles]")
@Api(value = "pizzas", description = "the pizzas API")
public interface PizzasApi {

    @ApiOperation(value = "deletes an existing pizza", nickname = "deletePizzaById", notes = "This operation deletes pizza with a given ID.", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Item successfully deleted"),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/pizzas/{pizzaId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deletePizzaById(@Min(0)@ApiParam(value = "a pizza's unique ID",required=true, allowableValues="") @PathVariable("pizzaId") Integer pizzaId);


    @ApiOperation(value = "returns the pizza with the given ID", nickname = "getPizzaById", notes = "By passing in a valid ID, you can find a pizza in the database.", response = Pizza.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "pizza found", response = Pizza.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/pizzas/{pizzaId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Pizza> getPizzaById(@Min(0)@ApiParam(value = "a pizza's unique ID",required=true, allowableValues="") @PathVariable("pizzaId") Integer pizzaId);


    @ApiOperation(value = "creates a new pizza", nickname = "newPizza", notes = "", response = Pizza.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "pizza created", response = Pizza.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class) })
    @RequestMapping(value = "/pizzas",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Pizza> newPizza(@ApiParam(value = "A JSON encoded pizza object" ,required=true )  @Valid @RequestBody Pizza body);


    @ApiOperation(value = "updates an existing pizza", nickname = "updatePizzaById", notes = "This operation updates information on a pizza with a given ID.", response = Pizza.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "item updated", response = Pizza.class),
        @ApiResponse(code = 400, message = "Bad data in request", response = Error.class),
        @ApiResponse(code = 404, message = "The specified resource was not found", response = Error.class) })
    @RequestMapping(value = "/pizzas/{pizzaId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Pizza> updatePizzaById(@ApiParam(value = "A pizza store with updated information" ,required=true )  @Valid @RequestBody Pizza body,@Min(0)@ApiParam(value = "a pizza's unique ID",required=true, allowableValues="") @PathVariable("pizzaId") Integer pizzaId);

}
